language: python
python:
  - "3.6.5"
services:
  - postgresql
env:
  global:
    - APP_SETTINGS = tesing
    - CODECOV_TOKEN="92ebdbf5-adeb-4fe0-b197-ef8315d43b9b"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

before_script:
  - psql -c "CREATE DATABASE store_db;" -U postgres
# command to run tests
script:
  - nosetests --with-cov --cov  tests/

after_success:
  - coveralls
  - codecov